### ISSUE TITLE
How can i change button color  and button text color?

### ISSUE THREAD

**Issue by iampawan** [fredericojssilva/ShowTipsView#10]
Please help ??

**Comment by iampawan** [comment]
@fredericojssilva

**Comment by fredericojssilva** [comment]
@iampawan Now you can´t. Between today and tomorrow I'll release an update with that. I let you know when it's done

**Comment by iampawan** [comment]
@fredericojssilva  thank you so much.. One more question .. Some times it crashes the app saying out of memory exception.
Here's the log:

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 3686412 byte allocation with 2003904 free bytes and 1956KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:838)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:815)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:782)
       at net.frederico.showtipsview.ShowTipsView.onDraw(ShowTipsView.java:118)
       at android.view.View.draw(View.java:15249)
       at android.view.View.updateDisplayListIfDirty(View.java:14185)
       at android.view.View.getDisplayList(View.java:14207)
       at android.view.View.draw(View.java:14977)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
       at android.view.View.draw(View.java:15252)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
       at android.view.View.updateDisplayListIfDirty(View.java:14185)
       at android.view.View.getDisplayList(View.java:14207)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2560)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2382)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

**Comment by fredericojssilva** [comment]
@iampawan Ok, I will check it.

**Comment by iampawan** [comment]
When you are updating the library? @fredericojssilva

**Comment by fredericojssilva** [comment]
@iampawan updated

Available methods to customize close button:
setCloseButtonColor(int color)
setCloseButtonTextColor
setButtonBackground(Drawable drawable)
